[build]
  publish = "."
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"
  external_node_modules = []
  included_files = []

[[redirects]]
  from = "/functions/swu"
  to = "/.netlify/functions/swu"
  status = 200
